"""
Django settings for Akounter project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

#import firebase_admin
#from firebase_admin import credentials

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'hlulw9q9*7!kixzoo_02e%o$kyeoczacz5@h-@o74fe2#k(3z='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    # django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party
    'channels',
    'rest_framework',
    'corsheaders',
    'django_seed',
    'django_rest_passwordreset',
    'django_filters',
    'thumbnails',
    'fcm_django',

    # custom
    'accounts',
    'master',
    'konnect',
    #'reminders',
    'tags',
    'helpers',
    #'plan',
    'Election',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://62.171.174.53:3000",
    "http://127.0.0.1:8000",
    "http://62.171.162.1:3000",
    "http://62.171.162.1",
]

ROOT_URLCONF = 'Akounter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'frontend', 'build')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Akounter.wsgi.application'
ASGI_APPLICATION = "Akounter.routing.application"

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000 # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000 # 5 MB


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'akounter_konnect',
        'USER': 'root',
        'PASSWORD': 'anant',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static_cdn"),
    os.path.join(BASE_DIR, 'frontend', 'build', 'static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.CustomTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES':(
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Channels
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],
#         },
#     },
# }

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'techfinsq@gmail.com' #test
EMAIL_HOST_PASSWORD = 'Ta1nm9@ay8'#test
EMAIL_PORT = 587
EMAIL_USE_TLS = True

THUMBNAILS = {
    'METADATA': {
        'BACKEND': 'thumbnails.backends.metadata.DatabaseBackend',
    },
    'STORAGE': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'SIZES':{
        'small': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 10, 'height': 10},
                {'PATH': 'thumbnails.processors.crop', 'width': 80, 'height': 80}
            ],
            'POST_PROCESSORS': [
                {
                    'PATH': 'thumbnails.post_processors.optimize',
                    'png_command': 'optipng -force -o7 "%(filename)s"',
                    'jpg_command': 'jpegoptim -f --strip-all "%(filename)s"',
                },
            ],
        },
        'large': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 150, 'height': 150},
                # {'PATH': 'thumbnails.processors.flip', 'direction': 'horizontal'}
            ],
        }
    }
}

# msg91 settings
# AUTH_KEY = '344506AEeONT4zF05f86dd5eP1'
# TEMPLATE_ID = '5f8ec8f61bfacc32795fa65f'
AUTH_KEY = '356613AZ8vspn6604f34efP1' 
TEMPLATE_ID = '60b08391f6981e5b935dfa82'

# firebase settings
FCM_DJANGO_SETTINGS = {
        # "FCM_SERVER_KEY": "AAAAgmBqIVM:APA91bGGtfN1MSZ4JZh33IrdKmL7ME8dvRuCwS0GRYv1nR6RViyL-m1APmTm1OoELubNZzC6tGI_sRJGTETdl-rwuiD9G4vbMuczF4j8ryUa2jGe8aGnm-HpMLzDxr6nZpYI7KRPwprF"
        # "FCM_SERVER_KEY": "AAAA9WmJLf8:APA91bEQB7YjYZwxHVLKRDMz_WwZPpGiIi8nkDmxhogME-_bdg1ut1s0jxOMeovFSxjITu4qx6Z6ig8J09jHmyoCAUB5GfFRC_BR1FUby-zCmZYq67GKFUJewLljt4cb_xQxKnGz-brj"
        "FCM_SERVER_KEY": "AAAAgmBqIVM:APA91bF1ktg6Apn9jj8_e8nCiUhCmSur-jzrKBZUiWg98sNYa9cAfwE4I1te9kPGuKSpstnV0zw5Ao9lz9lzgzApghJP8OadWaf-NcjoDjf4G4115yLJSG4ScXABffnlJoqo--YzIfu4"
        # "FCM_SERVER_KEY": "AAAAgJ7i_LY:APA91bHNeg14ZbS2xTnkT-JUJiD-BCUBigrl_mtiEejR7rdiJMMf66gFhEYWxg6OfKL8ZUqaDuTyXtmVsRaXg6KgPkH3z5HXW6E3S0RhVYbYLnFiTOVXRVg0U6w_Ved5koEIO01Qj5hC"

}
# PROJECT_APP = os.path.basename(BASE_DIR)
# print(BASE_DIR)
#cred = credentials.Certificate(os.path.join(BASE_DIR, 'akounter-konnect-firebase-adminsdk-o81xh-171d805204.json'))
#firebase_admin.initialize_app(cred)
