# Generated by Django 3.1.5 on 2022-02-01 16:13

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re
import thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Required. 30 characters or fewer. Letters, numbers and @/./+/-/_ characters', max_length=75, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Enter a valid username.', 'invalid')], verbose_name='username')),
                ('first_name', models.CharField(max_length=250, verbose_name='first name')),
                ('last_name', models.CharField(max_length=250, verbose_name='last name')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='mobile')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site with all the rights.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated on')),
            ],
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('device_id', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='LoginDeviceTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.CharField(blank=True, max_length=254, null=True)),
                ('device_os', models.CharField(blank=True, max_length=254, null=True)),
                ('os_version', models.CharField(blank=True, max_length=254, null=True)),
                ('device_model', models.CharField(blank=True, max_length=254, null=True)),
                ('device_name', models.CharField(blank=True, max_length=254, null=True)),
                ('login_token', models.CharField(blank=True, max_length=254, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated on')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=60)),
                ('permissions', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated on')),
            ],
            options={
                'permissions': [('view_own_role', 'Can view own role')],
            },
        ),
        migrations.CreateModel(
            name='SignupReferralCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated on')),
            ],
        ),
        migrations.CreateModel(
            name='SignupReferralCodeUserMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated on')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated on')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn_no', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile-pic')),
                ('profile_pic_icon', thumbnails.fields.ImageField(blank=True, null=True, upload_to='profile-pic-icon')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='cover-pic')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_mobile_1', models.CharField(blank=True, max_length=50, null=True)),
                ('alt_mobile_2', models.CharField(blank=True, max_length=50, null=True)),
                ('alt_email_1', models.CharField(blank=True, max_length=200, null=True)),
                ('alt_email_2', models.CharField(blank=True, max_length=200, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('company_pincode', models.CharField(blank=True, max_length=25, null=True)),
                ('home_pincode', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=8, null=True, verbose_name='Gender')),
                ('about', models.TextField(blank=True, null=True)),
                ('active_voter', models.CharField(blank=True, max_length=50, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('mobile_verified', models.BooleanField(default=False)),
                ('cop', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated on')),
            ],
            options={
                'permissions': [('view_own_userdetail', 'Can view own user detail')],
            },
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('activities', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated on')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrolemap_created_by', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrolemap_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_own_userrolemap', 'Can view own user role map')],
            },
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userexperience_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_own_userexperience', 'Can view own user experience')],
            },
        ),
    ]
