# Generated by Django 3.1.5 on 2022-02-01 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('konnect', '0002_auto_20220201_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexperience',
            name='employment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.employmenttype'),
        ),
        migrations.AddField(
            model_name='userexperience',
            name='experience_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userexperience',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.city'),
        ),
        migrations.AddField(
            model_name='userexperience',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userexperience_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usereducation_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='education_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usereducation_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='company_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdetail_company_city', to='master.city'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdetail_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='home_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdetail_home_city', to='master.city'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdetail_country', to='master.country'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.profession'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.region'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdetail_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_detail_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.campaign'),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signupreferralcodeusermap',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signupreferralcodeusermap_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signupreferralcodeusermap',
            name='referral_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.signupreferralcode'),
        ),
        migrations.AddField(
            model_name='signupreferralcodeusermap',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signupreferralcodeusermap_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signupreferralcodeusermap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signupreferralcode',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signupreferralcode_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signupreferralcode',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signupreferralcode_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.campaign'),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logindevicetrack',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logindevicetrack_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logindevicetrack',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logindevicetrack_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logindevicetrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitylog_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='konnect_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konnect.connection'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitylog_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
