# Generated by Django 3.1.5 on 2022-02-01 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('konnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_type', models.CharField(max_length=100)),
                ('rel_id', models.IntegerField(blank=True, null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('tag_value', models.CharField(max_length=200)),
                ('tag_description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_created_by', to=settings.AUTH_USER_MODEL)),
                ('meeting_connection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_meeting_connection', to='konnect.connection')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_own_tag', 'Can view own tag')],
            },
        ),
        migrations.CreateModel(
            name='MentionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_tag_name', models.CharField(max_length=100)),
                ('mention_tag_table', models.CharField(max_length=100)),
                ('mention_tag_column', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentiontag_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentiontag_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_own_mentiontag', 'Can view own mention tag')],
            },
        ),
        migrations.CreateModel(
            name='DropDownTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dd_tag_name', models.CharField(max_length=100)),
                ('dd_tag_value', models.TextField()),
                ('dd_default_tag_value', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Updated on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdowntag_created_by', to=settings.AUTH_USER_MODEL)),
                ('dd_tag_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdowntag_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_own_dropdowntag', 'Can view own dropdown tag')],
            },
        ),
    ]
