# Generated by Django 3.1.5 on 2022-02-01 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('konnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontemp',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectiontemp_home_city', to='master.city'),
        ),
        migrations.AddField(
            model_name='connectiontemp',
            name='company_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectiontemp_company_city', to='master.city'),
        ),
        migrations.AddField(
            model_name='connectiontemp',
            name='connection_centralized',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectiontemp_centralized', to='master.centralizeddata'),
        ),
        migrations.AddField(
            model_name='connectiontemp',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectiontemp_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectiontemp',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectiontemp_country', to='master.country'),
        ),
        migrations.AddField(
            model_name='connectiontemp',
            name='parent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parenttemp_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectiontemp',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.profession'),
        ),
        migrations.AddField(
            model_name='connectiontemp',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectiontemp_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectiontemp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectiontemp_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_home_city', to='master.city'),
        ),
        migrations.AddField(
            model_name='connection',
            name='company_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_company_city', to='master.city'),
        ),
        migrations.AddField(
            model_name='connection',
            name='connection_centralized',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_centralized', to='master.centralizeddata'),
        ),
        migrations.AddField(
            model_name='connection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_country', to='master.country'),
        ),
        migrations.AddField(
            model_name='connection',
            name='parent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.profession'),
        ),
        migrations.AddField(
            model_name='connection',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.region'),
        ),
        migrations.AddField(
            model_name='connection',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectapproval',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectapproval_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectapproval',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectapproval_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
